export const RESTART_AUTH_RESPONSE = 'RESTART_AUTH_RESPONSE';

export const LOADING = 'LOADING';

export const CODE_ERROR = 'CODE_ERROR';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const LOAD_PROFILE_SUCCESS = 'LOAD_PROFILE_SUCCESS';
export const LOAD_PROFILE_ERROR = 'LOAD_PROFILE_ERROR';

export const ROADTAX_SUCCESS = 'ROADTAX_SUCCESS';
export const ROADTAX_ERROR = 'ROADTAX_ERROR';

export const LOAD_ROADTAX_SUCCESS = 'LOAD_ROADTAX_SUCCESS';
export const LOAD_ROADTAX_ERROR = 'LOAD_ROADTAX_ERROR';

export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';

